//
// Generated file, do not edit! Created by opp_msgtool 6.0 from reqiotext.msg.
//

#ifndef __REQIOTEXT_M_H
#define __REQIOTEXT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Sdnmsg;
/**
 * Class generated from <tt>reqiotext.msg:16</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message Sdnmsg
 * {
 *     int source;
 *     int destination;
 *     int msg_state;//1 start network// 0 normal
 *     double mount[30];//data
 *     short hope;
 * 
 * }
 * </pre>
 */
class Sdnmsg : public ::omnetpp::cMessage
{
  protected:
    int source = 0;
    int destination = 0;
    int msg_state = 0;
    double mount[30] = {0};
    short hope = 0;

  private:
    void copy(const Sdnmsg& other);

  protected:
    bool operator==(const Sdnmsg&) = delete;

  public:
    Sdnmsg(const char *name=nullptr, short kind=0);
    Sdnmsg(const Sdnmsg& other);
    virtual ~Sdnmsg();
    Sdnmsg& operator=(const Sdnmsg& other);
    virtual Sdnmsg *dup() const override {return new Sdnmsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSource() const;
    virtual void setSource(int source);

    virtual int getDestination() const;
    virtual void setDestination(int destination);

    virtual int getMsg_state() const;
    virtual void setMsg_state(int msg_state);

    virtual size_t getMountArraySize() const;
    virtual double getMount(size_t k) const;
    virtual void setMount(size_t k, double mount);

    virtual short getHope() const;
    virtual void setHope(short hope);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Sdnmsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Sdnmsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Sdnmsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<Sdnmsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __REQIOTEXT_M_H

